User.create!([
  {username: "mickey", password_digest: "$2a$10$buj6v9DZVIze6yBM7WQmiuyQVCu8JMI6YZrJcH7/w185pUWvaRel6", session_token: "wuZOet0IJ+psIiRK1NJVcg=="},
  {username: "guest", password_digest: "$2a$10$saFCvDd4ANdiq9qNaP1mNeDqwQfh664hTOLuh.PDOq4GCcQzLqaty", session_token: "yDWUTtrQnEpWEcOOr6VCRg=="},
  {username: "fernando", password_digest: "$2a$10$ZbtsyFapskOUHzQezHw7AeHSEy4USjJu3roh6o0fg79XIeV7RNnae", session_token: "TmCp5QY578XslVSnJUKBBQ=="},
  {username: "quirien", password_digest: "$2a$10$9iC2JAMgRqw29a1HStWT1uMZqQDgYxE1WSQiBRwDwR7Kfl2gITxOK", session_token: "ewsf12yQEh5PTFdhE2QEbg=="},
  {username: "yellowwolf", password_digest: "$2a$10$3pLEiW8mS7Kjp8OOCy.hBOVclh/rjGFdK.DapbR5wry4ox8zCz7ey", session_token: "2VcsJQprrjBTZEQpz+mqzw=="},
  {username: "holly", password_digest: "$2a$10$XFL0op6ZCS99GMz0Szipw.kJS8FVlKNG/BVDFdmYWrReMBx3aQEr2", session_token: "PAxcP6ELadRFGRvhmKUfOQ=="},
  {username: "svenja", password_digest: "$2a$10$qOkAAIN5QnRWrA8pHF5Ak.PzzxSUceQydbE5aGih1FJP8G/LCP/J.", session_token: "R9MlzAJNurJiWAWp89I4ow=="},
  {username: "sirko", password_digest: "$2a$10$kZXkFrlghqDXkCm.xY688.KC.RawfFjodZ5nXy5txtf3ndHCYb8Je", session_token: "JF9opPGC240F3YxFcPx4pQ=="},
  {username: "arthur", password_digest: "$2a$10$S/AoC8jjQ4xsnGq2z46Bn.jIlHd13F7CZYrGATS2o7JtOAXdsTWUm", session_token: "w8bM8/53+ruXn5TpSqGyzg=="},
  {username: "heidi", password_digest: "$2a$10$CZ8qoG6JcuiVjGiKoXO8DuLWMHZepEsEX2KBhsdZK9TlvoU6HksTG", session_token: "ilh/inLycQW+WgocEexcpQ=="},
  {username: "yolanda", password_digest: "$2a$10$6lGrXuDhbzvprGYcD6rHtuHNs5iRHS6E.95I7YgIPsAmphG7puNeC", session_token: "I3qBbMBkvupnYam/ZmZNAw=="},
  {username: "téo", password_digest: "$2a$10$IDYy.3IWvKAwtSrxA073r.hqohVn9HxkL0xmVDUVurbVHBbZiPNkm", session_token: "GxcNX2JwDhjIuBWitz111A=="},
  {username: "toni", password_digest: "$2a$10$6Adh5z9Yv.QxqcD3efha2OJaZUcN8GebsCNSkS/VDI5HqtIi3Afnu", session_token: "j9mhbZvOIPZiow/3t4ampQ=="},
  {username: "luca", password_digest: "$2a$10$uJSXHUHCDKElmJ0LWzmwbOzW/wwI5UJupixvtSZw7J4hrJhDl/PLG", session_token: "0vgIbBmOae2wVW0ltqStaQ=="},
  {username: "ronaldo", password_digest: "$2a$10$Qz3tQPgRbhYITyANLPdg8Ojr/.fc4c0VdmJdAxrx/YOl7WOpXNUy6", session_token: "H9lHl6TeXWTCdmgJs+/ayQ=="}
])
Video.create!([
  {title: "V NICE", link_url: "https://vimeo.com/177410774", user_id: nil, thumbnail: "https://i.vimeocdn.com/video/584816841_295x166.jpg", embed_url: "<iframe src=\"https://player.vimeo.com/video/177410774?autoplay=1\" width=\"492\" height=\"360\" frameborder=\"0\" title=\"V NICE\" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>"},
  {title: "HUF NYC", link_url: "https://vimeo.com/176817356", user_id: nil, thumbnail: "https://i.vimeocdn.com/video/585814742_640.jpg", embed_url: "<iframe src=\"https://player.vimeo.com/video/176817356?autoplay=1\" width=\"640\" height=\"360\" frameborder=\"0\" title=\"HUF NYC\" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>"},
  {title: "Thomas Genon - This Is Home", link_url: "https://vimeo.com/178285132", user_id: nil, thumbnail: "https://i.vimeocdn.com/video/585865122_640.jpg", embed_url: "<iframe src=\"https://player.vimeo.com/video/178285132?autoplay=1\" width=\"640\" height=\"320\" frameborder=\"0\" title=\"Thomas Genon - This Is Home\" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>"},
  {title: "LEON GARCIA", link_url: "https://vimeo.com/179408693", user_id: nil, thumbnail: "https://i.vimeocdn.com/video/587324957_640.jpg", embed_url: "<iframe src=\"https://player.vimeo.com/video/179408693?autoplay=1\" width=\"640\" height=\"360\" frameborder=\"0\" title=\"LEON GARCIA\" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>"},
  {title: "aRm1", link_url: "https://vimeo.com/179197844", user_id: nil, thumbnail: "https://i.vimeocdn.com/video/587668294_640.jpg", embed_url: "<iframe src=\"https://player.vimeo.com/video/179197844?autoplay=1\" width=\"640\" height=\"360\" frameborder=\"0\" title=\"aRm1\" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>"},
  {title: "RIDE : SUMMER 16", link_url: "https://vimeo.com/179956450", user_id: nil, thumbnail: "https://i.vimeocdn.com/video/588963501_640.jpg", embed_url: "<iframe src=\"https://player.vimeo.com/video/179956450?autoplay=1\" width=\"640\" height=\"360\" frameborder=\"0\" title=\"RIDE : SUMMER 16\" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>"},
  {title: "Nixon | Welcome Kelia Moniz and Leila Hurst to the Team", link_url: "https://vimeo.com/179006367", user_id: nil, thumbnail: "https://i.vimeocdn.com/video/586794098_640.jpg", embed_url: "<iframe src=\"https://player.vimeo.com/video/179006367?autoplay=1\" width=\"640\" height=\"360\" frameborder=\"0\" title=\"Nixon | Welcome Kelia Moniz and Leila Hurst to the Team\" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>"},
  {title: "LOST TRACK Australia", link_url: "https://vimeo.com/181448784", user_id: nil, thumbnail: "https://i.vimeocdn.com/video/590190918_640.jpg", embed_url: "<iframe src=\"https://player.vimeo.com/video/181448784?autoplay=1\" width=\"640\" height=\"360\" frameborder=\"0\" title=\"LOST TRACK Australia\" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>"},
  {title: "MFTBRAND 2016.9.10『 western 』", link_url: "https://vimeo.com/182136086", user_id: nil, thumbnail: "https://i.vimeocdn.com/video/590931781_640.jpg", embed_url: "<iframe src=\"https://player.vimeo.com/video/182136086?autoplay=1\" width=\"640\" height=\"360\" frameborder=\"0\" title=\"MFTBRAND 2016.9.10『 western 』\" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>"},
  {title: "Nixon | The Four Moors: a journey through Sardinia", link_url: "https://vimeo.com/182968512", user_id: nil, thumbnail: "https://i.vimeocdn.com/video/592071578_640.jpg", embed_url: "<iframe src=\"https://player.vimeo.com/video/182968512?autoplay=1\" width=\"640\" height=\"360\" frameborder=\"0\" title=\"Nixon | The Four Moors: a journey through Sardinia\" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>"},
  {title: "Moments at Elevation", link_url: "https://vimeo.com/182648649", user_id: nil, thumbnail: "https://i.vimeocdn.com/video/591626369_640.jpg", embed_url: "<iframe src=\"https://player.vimeo.com/video/182648649?autoplay=1\" width=\"640\" height=\"360\" frameborder=\"0\" title=\"Moments at Elevation\" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>"},
  {title: "UEFA", link_url: "https://vimeo.com/182666400", user_id: nil, thumbnail: "https://i.vimeocdn.com/video/591641679_640.jpg", embed_url: "<iframe src=\"https://player.vimeo.com/video/182666400?autoplay=1\" width=\"640\" height=\"360\" frameborder=\"0\" title=\"UEFA\" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>"},
  {title: "Pattern of Life", link_url: "https://vimeo.com/190986464", user_id: nil, thumbnail: "https://i.vimeocdn.com/video/601858389_640.jpg", embed_url: "<iframe src=\"https://player.vimeo.com/video/190986464?autoplay=1\" width=\"640\" height=\"360\" frameborder=\"0\" title=\"Pattern of Life\" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>"},
  {title: "Journal 3 - The Pale Mountains road", link_url: "https://vimeo.com/188261946", user_id: nil, thumbnail: "https://i.vimeocdn.com/video/598282096_640.jpg", embed_url: "<iframe src=\"https://player.vimeo.com/video/188261946?autoplay=1\" width=\"640\" height=\"360\" frameborder=\"0\" title=\"Journal 3 - The Pale Mountains road\" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>"},
  {title: "LAPSE", link_url: "https://vimeo.com/189530509", user_id: nil, thumbnail: "https://i.vimeocdn.com/video/600018957_640.jpg", embed_url: "<iframe src=\"https://player.vimeo.com/video/189530509?autoplay=1\" width=\"640\" height=\"360\" frameborder=\"0\" title=\"LAPSE\" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>"},
  {title: "Road surf trip from San Francisco to Los Angeles", link_url: "https://vimeo.com/183410559", user_id: nil, thumbnail: "https://i.vimeocdn.com/video/592609869_640.jpg", embed_url: "<iframe src=\"https://player.vimeo.com/video/183410559?autoplay=1\" width=\"640\" height=\"360\" frameborder=\"0\" title=\"Road surf trip from San Francisco to Los Angeles\" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>"},
  {title: "Prepare with Mariano Rivera", link_url: "https://vimeo.com/179348115", user_id: nil, thumbnail: "https://i.vimeocdn.com/video/592731571_640.jpg", embed_url: "<iframe src=\"https://player.vimeo.com/video/179348115?autoplay=1\" width=\"640\" height=\"360\" frameborder=\"0\" title=\"Prepare with Mariano Rivera\" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>"},
  {title: "Johanna Under The Ice - NOWNESS", link_url: "https://vimeo.com/181027959", user_id: nil, thumbnail: "https://i.vimeocdn.com/video/589460763_640.jpg", embed_url: "<iframe src=\"https://player.vimeo.com/video/181027959?autoplay=1\" width=\"640\" height=\"360\" frameborder=\"0\" title=\"Johanna Under The Ice - NOWNESS\" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>"},
  {title: "First Crack", link_url: "https://vimeo.com/184107981", user_id: nil, thumbnail: "https://i.vimeocdn.com/video/593506234_640.jpg", embed_url: "<iframe src=\"https://player.vimeo.com/video/184107981?autoplay=1\" width=\"640\" height=\"360\" frameborder=\"0\" title=\"First Crack\" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>"},
  {title: "Tinto de Verano", link_url: "https://vimeo.com/181964440", user_id: nil, thumbnail: "https://i.vimeocdn.com/video/595586486_640.jpg", embed_url: "<iframe src=\"https://player.vimeo.com/video/181964440?autoplay=1\" width=\"640\" height=\"320\" frameborder=\"0\" title=\"Tinto de Verano\" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>"},
  {title: "lords of the chiken 8", link_url: "https://vimeo.com/186044683", user_id: nil, thumbnail: "https://i.vimeocdn.com/video/596175114_640.jpg", embed_url: "<iframe src=\"https://player.vimeo.com/video/186044683?autoplay=1\" width=\"640\" height=\"360\" frameborder=\"0\" title=\"lords of the chiken 8\" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>"},
  {title: "Tom van Steenbergen - This Is Home", link_url: "https://vimeo.com/185736985", user_id: nil, thumbnail: "https://i.vimeocdn.com/video/595580227_640.jpg", embed_url: "<iframe src=\"https://player.vimeo.com/video/185736985?autoplay=1\" width=\"640\" height=\"320\" frameborder=\"0\" title=\"Tom van Steenbergen - This Is Home\" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>"},
  {title: "NATURAL PLAYGROUND.", link_url: "https://vimeo.com/183035588", user_id: nil, thumbnail: "https://i.vimeocdn.com/video/596357930_640.jpg", embed_url: "<iframe src=\"https://player.vimeo.com/video/183035588?autoplay=1\" width=\"640\" height=\"360\" frameborder=\"0\" title=\"NATURAL PLAYGROUND.\" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>"},
  {title: "PRETTY FAR NORTH", link_url: "https://vimeo.com/187094433", user_id: nil, thumbnail: "https://i.vimeocdn.com/video/597079255_640.jpg", embed_url: "<iframe src=\"https://player.vimeo.com/video/187094433?autoplay=1\" width=\"640\" height=\"360\" frameborder=\"0\" title=\"PRETTY FAR NORTH\" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>"},
  {title: "Journal 3 - The Pale Mountains road", link_url: "https://vimeo.com/188261946", user_id: nil, thumbnail: "https://i.vimeocdn.com/video/598282096_640.jpg", embed_url: "<iframe src=\"https://player.vimeo.com/video/188261946?autoplay=1\" width=\"640\" height=\"360\" frameborder=\"0\" title=\"Journal 3 - The Pale Mountains road\" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>"},
  {title: "Bowl Recap - Teilhard Volk", link_url: "https://vimeo.com/190344571", user_id: nil, thumbnail: "https://i.vimeocdn.com/video/601031337_640.jpg", embed_url: "<iframe src=\"https://player.vimeo.com/video/190344571?autoplay=1\" width=\"640\" height=\"360\" frameborder=\"0\" title=\"Bowl Recap - Teilhard Volk\" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>"},
  {title: "El Niño 2016", link_url: "https://vimeo.com/173198687", user_id: nil, thumbnail: "https://i.vimeocdn.com/video/579384311_640.jpg", embed_url: "<iframe src=\"https://player.vimeo.com/video/173198687?autoplay=1\" width=\"640\" height=\"360\" frameborder=\"0\" title=\"El Ni&ntilde;o 2016\" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>"},
  {title: "China: A Skier's Journey", link_url: "https://vimeo.com/175629655", user_id: nil, thumbnail: "https://i.vimeocdn.com/video/596364219_640.jpg", embed_url: "<iframe src=\"https://player.vimeo.com/video/175629655?autoplay=1\" width=\"640\" height=\"360\" frameborder=\"0\" title=\"China: A Skier&#039;s Journey\" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>"},
  {title: "HippyTree / Dos Días at Middles", link_url: "https://vimeo.com/189083066", user_id: nil, thumbnail: "https://i.vimeocdn.com/video/599294845_640.jpg", embed_url: "<iframe src=\"https://player.vimeo.com/video/189083066?autoplay=1\" width=\"640\" height=\"360\" frameborder=\"0\" title=\"HippyTree / Dos D&iacute;as at Middles\" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>"},
  {title: "A Maine Point Of View", link_url: "https://vimeo.com/190595693", user_id: nil, thumbnail: "https://i.vimeocdn.com/video/601491035_640.jpg", embed_url: "<iframe src=\"https://player.vimeo.com/video/190595693?autoplay=1\" width=\"640\" height=\"360\" frameborder=\"0\" title=\"A Maine Point Of View\" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>"},
  {title: "Cope: Surviving in the NBA", link_url: "https://vimeo.com/187180866", user_id: nil, thumbnail: "https://i.vimeocdn.com/video/596849394_640.jpg", embed_url: "<iframe src=\"https://player.vimeo.com/video/187180866?autoplay=1\" width=\"640\" height=\"360\" frameborder=\"0\" title=\"Cope: Surviving in the NBA\" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>"},
  {title: "Perspective", link_url: "https://vimeo.com/189948798", user_id: nil, thumbnail: "https://i.vimeocdn.com/video/600451805_640.jpg", embed_url: "<iframe src=\"https://player.vimeo.com/video/189948798?autoplay=1\" width=\"640\" height=\"360\" frameborder=\"0\" title=\"Perspective\" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>"},
  {title: "THE BOX", link_url: "https://vimeo.com/190514742", user_id: nil, thumbnail: "https://i.vimeocdn.com/video/601198466_640.jpg", embed_url: "<iframe src=\"https://player.vimeo.com/video/190514742?autoplay=1\" width=\"640\" height=\"360\" frameborder=\"0\" title=\"THE BOX\" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>"},
  {title: "THE NORTH", link_url: "https://vimeo.com/187286930", user_id: nil, thumbnail: "https://i.vimeocdn.com/video/597074207_640.jpg", embed_url: "<iframe src=\"https://player.vimeo.com/video/187286930?autoplay=1\" width=\"640\" height=\"360\" frameborder=\"0\" title=\"THE NORTH\" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>"},
  {title: "Peaks of Adventure in Dolomiti Paganella", link_url: "https://vimeo.com/190530963", user_id: nil, thumbnail: "https://i.vimeocdn.com/video/601221279_640.jpg", embed_url: "<iframe src=\"https://player.vimeo.com/video/190530963?autoplay=1\" width=\"640\" height=\"360\" frameborder=\"0\" title=\"Peaks of Adventure in Dolomiti Paganella\" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>"},
  {title: "Mavericks · November 9th", link_url: "https://vimeo.com/191020571", user_id: nil, thumbnail: "https://i.vimeocdn.com/video/601887760_640.jpg", embed_url: "<iframe src=\"https://player.vimeo.com/video/191020571?autoplay=1\" width=\"640\" height=\"360\" frameborder=\"0\" title=\"Mavericks &middot; November 9th\" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>"},
  {title: "Snowmads - A Journey Towards Eastern Suns | Official Trailer", link_url: "https://vimeo.com/187324457", user_id: nil, thumbnail: "https://i.vimeocdn.com/video/597028368_640.jpg", embed_url: "<iframe src=\"https://player.vimeo.com/video/187324457?autoplay=1\" width=\"640\" height=\"360\" frameborder=\"0\" title=\"Snowmads - A Journey Towards Eastern Suns | Official Trailer\" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>"},
  {title: "Race to the Rock: 2016", link_url: "https://vimeo.com/186203426", user_id: nil, thumbnail: "https://i.vimeocdn.com/video/596191178_640.jpg", embed_url: "<iframe src=\"https://player.vimeo.com/video/186203426?autoplay=1\" width=\"640\" height=\"360\" frameborder=\"0\" title=\"Race to the Rock: 2016\" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>"},
  {title: "Nike x Chance The Rapper - We The People", link_url: "https://vimeo.com/177833573", user_id: nil, thumbnail: "https://i.vimeocdn.com/video/600970678_640.jpg", embed_url: "<iframe src=\"https://player.vimeo.com/video/177833573?autoplay=1\" width=\"640\" height=\"360\" frameborder=\"0\" title=\"Nike x Chance The Rapper - We The People\" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>"},
  {title: "VERTICAL LINES SURF FILM", link_url: "https://vimeo.com/190827005", user_id: nil, thumbnail: "https://i.vimeocdn.com/video/601624803_640.jpg", embed_url: "<iframe src=\"https://player.vimeo.com/video/190827005?autoplay=1\" width=\"640\" height=\"360\" frameborder=\"0\" title=\"VERTICAL LINES SURF FILM\" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>"}
])
Comment.create!([
  {video_id: 1, user_id: 1, body: "Holy crap. This changed my life."},
  {video_id: 12, user_id: 1, body: "This rocks my socks off and I wear sandals."},
  {video_id: 20, user_id: 1, body: "Really cool video. Loved how you got the angles."},
  {video_id: 17, user_id: 1, body: "This was sick!"},
  {video_id: 17, user_id: 2, body: "Wow. So glad I watched this"},
  {video_id: 22, user_id: 14, body: "Great video, can't wait to share this with my mom"},
  {video_id: 24, user_id: 14, body: "coolest. video. ever."},
  {video_id: 8, user_id: 14, body: "Duddddeeeee"},
  {video_id: 30, user_id: 14, body: "Seriously, what did I just watch?"},
  {video_id: 2, user_id: 4, body: "Bruh, I'm speechless."}
])
Like.create!([
  {user_id: 1, video_id: 5},
  {user_id: 1, video_id: 6},
  {user_id: 1, video_id: 16},
  {user_id: 1, video_id: 19},
  {user_id: 1, video_id: 20},
  {user_id: 1, video_id: 35},
  {user_id: 1, video_id: 25},
  {user_id: 1, video_id: 18},
  {user_id: 2, video_id: 5},
  {user_id: 2, video_id: 6},
  {user_id: 2, video_id: 16},
  {user_id: 2, video_id: 19},
  {user_id: 2, video_id: 20},
  {user_id: 2, video_id: 35},
  {user_id: 2, video_id: 25},
  {user_id: 2, video_id: 18},
  {user_id: 2, video_id: 2},
  {user_id: 2, video_id: 3},
  {user_id: 2, video_id: 14},
  {user_id: 2, video_id: 36},
  {user_id: 3, video_id: 1},
  {user_id: 3, video_id: 2},
  {user_id: 3, video_id: 3},
  {user_id: 3, video_id: 4},
  {user_id: 3, video_id: 5},
  {user_id: 3, video_id: 10},
  {user_id: 3, video_id: 11},
  {user_id: 3, video_id: 12},
  {user_id: 3, video_id: 13},
  {user_id: 3, video_id: 14},
  {user_id: 3, video_id: 18},
  {user_id: 3, video_id: 21},
  {user_id: 3, video_id: 22},
  {user_id: 3, video_id: 30},
  {user_id: 3, video_id: 31},
  {user_id: 4, video_id: 5},
  {user_id: 4, video_id: 6},
  {user_id: 4, video_id: 16},
  {user_id: 4, video_id: 19},
  {user_id: 4, video_id: 20},
  {user_id: 4, video_id: 35},
  {user_id: 4, video_id: 25},
  {user_id: 4, video_id: 18},
  {user_id: 4, video_id: 22},
  {user_id: 4, video_id: 34},
  {user_id: 5, video_id: 5},
  {user_id: 5, video_id: 8},
  {user_id: 5, video_id: 13},
  {user_id: 5, video_id: 18},
  {user_id: 5, video_id: 22},
  {user_id: 5, video_id: 26},
  {user_id: 5, video_id: 29},
  {user_id: 5, video_id: 31},
  {user_id: 5, video_id: 35},
  {user_id: 6, video_id: 3},
  {user_id: 6, video_id: 6},
  {user_id: 6, video_id: 9},
  {user_id: 6, video_id: 12},
  {user_id: 6, video_id: 15},
  {user_id: 6, video_id: 18},
  {user_id: 6, video_id: 21},
  {user_id: 6, video_id: 24},
  {user_id: 6, video_id: 27},
  {user_id: 6, video_id: 30},
  {user_id: 6, video_id: 33},
  {user_id: 7, video_id: 7},
  {user_id: 7, video_id: 10},
  {user_id: 7, video_id: 13},
  {user_id: 7, video_id: 16},
  {user_id: 8, video_id: 16},
  {user_id: 8, video_id: 8},
  {user_id: 8, video_id: 24},
  {user_id: 8, video_id: 22},
  {user_id: 8, video_id: 38},
  {user_id: 9, video_id: 9},
  {user_id: 9, video_id: 18},
  {user_id: 9, video_id: 27},
  {user_id: 9, video_id: 36},
  {user_id: 9, video_id: 3},
  {user_id: 9, video_id: 6}
])
